export const mockDestinations = [
  {
    preferenciaDestino: 'Playa',
    preferenciaClimatica: 'Caluroso',
    preferenciaActividad: 'Relax y bienestar',
    preferenciaAlojamiento: 'Hotel de lujo',
    duracionViaje: '1-2 semanas',
    edad: 'Menos de 30 años',
    posibleDestinoAmerica: 'Playa del Carmen, México',
    posibleDestinoEuropa: 'Santorini, Grecia',
  },
  {
    preferenciaDestino: 'Playa',
    preferenciaClimatica: 'Caluroso',
    preferenciaActividad: 'Cultura y museos',
    preferenciaAlojamiento: 'Airbnb',
    duracionViaje: 'Menos de una semana',
    edad: 'Menos de 30 años',
    posibleDestinoAmerica: 'Cartagena, Colombia',
    posibleDestinoEuropa: 'Barcelona, España',
  },
  {
    preferenciaDestino: 'Playa',
    preferenciaClimatica: 'Templado',
    preferenciaActividad: 'Cultura y museos',
    preferenciaAlojamiento: 'Hotel de lujo',
    duracionViaje: '1-2 semanas',
    edad: '30-50 años',
    posibleDestinoAmerica: 'Rio de Janeiro, Brasil',
    posibleDestinoEuropa: 'Lisboa, Portugal',
  },
  {
    preferenciaDestino: 'Montaña',
    preferenciaClimatica: 'Frío',
    preferenciaActividad: 'Deportes y aventuras',
    preferenciaAlojamiento: 'Albergue',
    duracionViaje: '1-2 semanas',
    edad: 'Menos de 30 años',
    posibleDestinoAmerica: 'Bariloche, Argentina',
    posibleDestinoEuropa: 'Interlaken, Suiza',
  },
  {
    preferenciaDestino: 'Montaña',
    preferenciaClimatica: 'Templado',
    preferenciaActividad: 'Cultura y museos',
    preferenciaAlojamiento: 'Airbnb',
    duracionViaje: '1-2 semanas',
    edad: 'Más de 50 años',
    posibleDestinoAmerica: 'Cusco, Perú',
    posibleDestinoEuropa: 'Granada, España',
  },
  {
    preferenciaDestino: 'Montaña',
    preferenciaClimatica: 'Frío',
    preferenciaActividad: 'Deportes y aventuras',
    preferenciaAlojamiento: 'Hotel de lujo',
    duracionViaje: '1-2 semanas',
    edad: '30-50 años',
    posibleDestinoAmerica: 'Banff, Canadá',
    posibleDestinoEuropa: 'Zermatt, Suiza',
  },
  {
    preferenciaDestino: 'Ciudad',
    preferenciaClimatica: 'Templado',
    preferenciaActividad: 'Cultura y museos',
    preferenciaAlojamiento: 'Hotel de lujo',
    duracionViaje: '1-2 semanas',
    edad: 'Más de 50 años',
    posibleDestinoAmerica: 'Nueva York, EE.UU.',
    posibleDestinoEuropa: 'París, Francia',
  },
  {
    preferenciaDestino: 'Ciudad',
    preferenciaClimatica: 'Templado',
    preferenciaActividad: 'Relax y bienestar',
    preferenciaAlojamiento: 'Airbnb',
    duracionViaje: 'Menos de una semana',
    edad: 'Menos de 30 años',
    posibleDestinoAmerica: 'Miami, EE.UU.',
    posibleDestinoEuropa: 'Viena, Austria',
  },
  {
    preferenciaDestino: 'Ciudad',
    preferenciaClimatica: 'Frío',
    preferenciaActividad: 'Cultura y museos',
    preferenciaAlojamiento: 'Hotel de lujo',
    duracionViaje: '1-2 semanas',
    edad: '30-50 años',
    posibleDestinoAmerica: 'Toronto, Canadá',
    posibleDestinoEuropa: 'Berlín, Alemania',
  },
  {
    preferenciaDestino: 'Playa',
    preferenciaClimatica: 'Caluroso',
    preferenciaActividad: 'Deportes y aventuras',
    preferenciaAlojamiento: 'Hostal',
    duracionViaje: '1-2 semanas',
    edad: 'Menos de 30 años',
    posibleDestinoAmerica: 'Tulum, México',
    posibleDestinoEuropa: 'Ibiza, España',
  },
  {
    preferenciaDestino: 'Montaña',
    preferenciaClimatica: 'Frío',
    preferenciaActividad: 'Cultura y museos',
    preferenciaAlojamiento: 'Airbnb',
    duracionViaje: '1-2 semanas',
    edad: 'Más de 50 años',
    posibleDestinoAmerica: 'Ushuaia, Argentina',
    posibleDestinoEuropa: 'Reykjavik, Islandia',
  },
  {
    preferenciaDestino: 'Playa',
    preferenciaClimatica: 'Templado',
    preferenciaActividad: 'Relax y bienestar',
    preferenciaAlojamiento: 'Airbnb',
    duracionViaje: 'Más de dos semanas',
    edad: 'Más de 50 años',
    posibleDestinoAmerica: 'Punta Cana, República Dominicana',
    posibleDestinoEuropa: 'Algarve, Portugal',
  },
  {
    preferenciaDestino: 'Ciudad',
    preferenciaClimatica: 'Templado',
    preferenciaActividad: 'Deportes y aventuras',
    preferenciaAlojamiento: 'Hotel de lujo',
    duracionViaje: 'Menos de una semana',
    edad: '30-50 años',
    posibleDestinoAmerica: 'Chicago, EE.UU.',
    posibleDestinoEuropa: 'Londres, Reino Unido',
  },
  {
    preferenciaDestino: 'Playa',
    preferenciaClimatica: 'Templado',
    preferenciaActividad: 'Cultura y museos',
    preferenciaAlojamiento: 'Albergue',
    duracionViaje: '1-2 semanas',
    edad: 'Menos de 30 años',
    posibleDestinoAmerica: 'San Juan, Puerto Rico',
    posibleDestinoEuropa: 'Niza, Francia',
  },
  {
    preferenciaDestino: 'Montaña',
    preferenciaClimatica: 'Templado',
    preferenciaActividad: 'Deportes y aventuras',
    preferenciaAlojamiento: 'Airbnb',
    duracionViaje: 'Más de dos semanas',
    edad: 'Menos de 30 años',
    posibleDestinoAmerica: 'Machu Picchu, Perú',
    posibleDestinoEuropa: 'Chamonix, Francia',
  },
  {
    preferenciaDestino: 'Ciudad',
    preferenciaClimatica: 'Caluroso',
    preferenciaActividad: 'Cultura y museos',
    preferenciaAlojamiento: 'Hotel de lujo',
    duracionViaje: '1-2 semanas',
    edad: 'Más de 50 años',
    posibleDestinoAmerica: 'Los Ángeles, EE.UU.',
    posibleDestinoEuropa: 'Roma, Italia',
  },
  {
    preferenciaDestino: 'Playa',
    preferenciaClimatica: 'Caluroso',
    preferenciaActividad: 'Cultura y museos',
    preferenciaAlojamiento: 'Hotel de lujo',
    duracionViaje: '1-2 semanas',
    edad: '30-50 años',
    posibleDestinoAmerica: 'Honolulu, Hawái',
    posibleDestinoEuropa: 'Malta',
  },
  {
    preferenciaDestino: 'Montaña',
    preferenciaClimatica: 'Frío',
    preferenciaActividad: 'Relax y bienestar',
    preferenciaAlojamiento: 'Airbnb',
    duracionViaje: '1-2 semanas',
    edad: 'Más de 50 años',
    posibleDestinoAmerica: 'Aspen, EE.UU.',
    posibleDestinoEuropa: 'Innsbruck, Austria',
  },
  {
    preferenciaDestino: 'Ciudad',
    preferenciaClimatica: 'Templado',
    preferenciaActividad: 'Cultura y museos',
    preferenciaAlojamiento: 'Albergue',
    duracionViaje: '1-2 semanas',
    edad: '30-50 años',
    posibleDestinoAmerica: 'Ciudad de México, México',
    posibleDestinoEuropa: 'Madrid, España',
  },
];
